spring:
  application:
    name: Web Template Spring Boot 2
  jmx:
    enabled: false
  freemarker: 
    template-loader-path: classpath:/templates/,classpath:org/springframework/web/servlet/view/freemarker
    suffix: .ftl   
    charset: UTF-8
  cache:
    jcache:      config: classpath:ehcache.xml  
server:
  servlet:
    context-path: /web-template-spring-boot-web
    session:
      timeout: 1800
      
  error:
    whitelabel:
      enabled: false
      

#logging:
#  level:
#    ROOT: DEBUG

# configurazione di default, viene fatto override per svilupo locale in application-dev.properties
logging:
  config: file:${catalina.home}/conf/web-template-spring-boot-web.log4j2.xml